### ISSUE TITLE
Investigate on various methods about similarity

### ISSUE THREAD

**Issue by k33g** [parakeet-nest/parakeet#18]
- Levenshtein distance
- Jaccard index
- ...

**Comment by codefromthecrypt** [comment]
what's the TL;DR; on these two approaches?

**Comment by k33g** [comment]
@codefromthecrypt I wanted to test if I could use the Jaccard index or Levenshtein distance to find similarities in chunks of the document.

JaccardSimilarityCoeff calculates the Jaccard similarity coefficient between two sets of strings.
  - For comparisons, the highest value is related to the best similarity
  - https://en.wikipedia.org/wiki/Jaccard_index
 
LevenshteinDistance calculates the Levenshtein distance between two strings.
  - For comparisons, the lowest distance is related to the best similarity

In the end, the results are not conclusive, but I keep the functions - I think I can use it if I use metadata with keywords

**Comment by codefromthecrypt** [comment]
gotcha and thanks, was curious if there were any clear leaders but seems still something to practice
