### ISSUE TITLE
add CreateEmbeddingWithOpenAI

### ISSUE THREAD

**Issue by codefromthecrypt** [parakeet-nest/parakeet#24]
I was able to port my demo code to use completion.ChatWithOpenAI, but then I noticed that CreateEmbedding is similarly using ollama. I would like to be able to OpenAI's embedding for that, even if I'm not using the platform. This allows use in ollama which emulates this, or anything similar that uses llama.cpp like its llama-server or https://github.com/Mozilla-Ocho/llamafile

**Comment by k33g** [comment]
@codefromthecrypt tested with `text-embedding-3-large`
https://github.com/parakeet-nest/parakeet/blob/main/examples/49-embeddings-memory-openai/main.go

**Comment by codefromthecrypt** [comment]
verified on my side, too (porting the elastic RAG example). Thanks!
